#!/bin/zsh

# Allow the `ubuntu` user to communicate with the host's Docker daemon.
# Used to build images to push to ECR during the deploy process.
[ -S /var/run/docker.sock ] && sudo chown ubuntu:ubuntu /var/run/docker.sock

# Load ENV vars.
cd /app
direnv allow
eval "$(direnv export zsh)"

# Validate ENV vars.
if [[ ! -v GIT_AUTHOR_EMAIL ]]; then
  echo "Add GIT_AUTHOR_EMAIL to .env.local.user and re-run .devcontainer/post-create."
  exit 1
fi

if [[ ! -v GIT_AUTHOR_NAME ]]; then
  echo "Add GIT_AUTHOR_NAME to .env.local.user and re-run .devcontainer/post-create."
  exit 1
fi

# Configure git.
git config --global user.email $GIT_AUTHOR_EMAIL
git config --global user.name $GIT_AUTHOR_NAME
git config --global --add safe.directory /app
git config --global pager.branch false

# Install dependencies.
# pnpm install && pnpm sync && pnpm post-create
